services:
  propertytaxgroup-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: propertytaxgroup
      POSTGRES_PASSWORD: localpass
      POSTGRES_DB: verceldb
    volumes:
      - propertytaxgroup-db:/var/lib/postgresql/data
    ports:
      # HOST:CONTAINER
      - "54320:5432"
    restart: on-failure
    networks:
      - default

  # pg_proxy:
  #   image: ghcr.io/neondatabase/wsproxy:latest
  #   environment:
  #     APPEND_PORT: 'propertytaxgroup-db:5432'
  #     ALLOW_ADDR_REGEX: '.*'
  #     LOG_TRAFFIC: 'true'
  #   ports:
  #     # Expose the WebSocket proxy port to the host machine,
  #     # this is where @vercel/postgres will connect
  #     - '54331:80'
  #   depends_on:
  #     - propertytaxgroup-db
  #   networks:
  #       - default

networks:
  default:
    name: internal
    external: true

volumes:
  propertytaxgroup-db:
  grafana_data:
