FROM python:3.12-slim

ENV BUILD_CACHE_BUST=1

WORKDIR /app

COPY requirements.txt ./
RUN pip install --no-cache-dir --upgrade pip \
 && pip install --no-cache-dir -r requirements.txt

COPY api/ ./api/

CMD ["uvicorn", "api.index:app", "--host=0.0.0.0", "--port=8000", "--reload"] 